package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	Server    ServerConfig
	LLM       LLMConfig
	Bootstrap BootstrapConfig
	PicoClaw  PicoClawConfig
}

type ServerConfig struct {
	ListenAddr string
	APIBaseURL string
}

type LLMConfig struct {
	BaseURL string
	APIKey  string
	ModelID string
}

type BootstrapConfig struct {
	ManagerImage string
}

type PicoClawConfig struct {
	AccessToken string
}

const (
	AppDirName         = ".csgclaw"
	RuntimeHomeDirName = "boxlite"
	ConfigFileName     = "config.toml"
	AgentsFileName     = "agents.json"
	IMStateFileName    = "im.json"

	DefaultListenAddr = "0.0.0.0:18080"
	DefaultAPIBaseURL = "http://127.0.0.1:18080"
	//DefaultLLMBaseURL   = "http://127.0.0.1:4000"
	DefaultLLMBaseURL          = "http://192.168.2.10:4000"
	DefaultLLMAPIKey           = "sk-1234567890"
	DefaultLLMModelID          = "minimax-m2.7"
	DefaultPicoClawAccessToken = "your_access_token"
	DefaultManagerImage        = "ghcr.io/russellluo/picoclaw:2026.3.27"
)

func DefaultDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home dir: %w", err)
	}
	return filepath.Join(home, AppDirName), nil
}

func DefaultPath() (string, error) {
	dir, err := DefaultDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, ConfigFileName), nil
}

func DefaultAgentsPath() (string, error) {
	dir, err := DefaultDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, AgentsFileName), nil
}

func DefaultIMStatePath() (string, error) {
	dir, err := DefaultDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, IMStateFileName), nil
}

func DefaultRuntimeHome() (string, error) {
	dir, err := DefaultDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, RuntimeHomeDirName), nil
}

func LoadDefault() (Config, error) {
	path, err := DefaultPath()
	if err != nil {
		return Config{}, err
	}
	return Load(path)
}

func Load(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Config{}, fmt.Errorf("config not found at %s; run `csgclaw onboard` first", path)
		}
		return Config{}, fmt.Errorf("read config: %w", err)
	}

	cfg := Config{}
	section := ""
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.Trim(line, "[]")
			continue
		}

		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return Config{}, fmt.Errorf("invalid line: %q", line)
		}

		key = strings.TrimSpace(key)
		value = strings.Trim(strings.TrimSpace(value), `"`)
		switch section {
		case "server":
			switch key {
			case "listen_addr":
				cfg.Server.ListenAddr = value
			case "api_base_url":
				cfg.Server.APIBaseURL = strings.TrimRight(value, "/")
			}
		case "llm":
			switch key {
			case "base_url":
				cfg.LLM.BaseURL = value
			case "api_key":
				cfg.LLM.APIKey = value
			case "model_id":
				cfg.LLM.ModelID = value
			}
		case "bootstrap":
			switch key {
			case "manager_image":
				cfg.Bootstrap.ManagerImage = value
			}
		case "picoclaw":
			switch key {
			case "access_token":
				cfg.PicoClaw.AccessToken = value
			case "send_token":
				cfg.PicoClaw.AccessToken = value
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return Config{}, fmt.Errorf("scan config: %w", err)
	}

	if cfg.Server.ListenAddr == "" {
		cfg.Server.ListenAddr = DefaultListenAddr
	}
	if cfg.Server.APIBaseURL == "" {
		cfg.Server.APIBaseURL = DefaultAPIBaseURL
	}
	if cfg.Bootstrap.ManagerImage == "" {
		cfg.Bootstrap.ManagerImage = DefaultManagerImage
	}
	if cfg.PicoClaw.AccessToken == "" {
		cfg.PicoClaw.AccessToken = DefaultPicoClawAccessToken
	}
	return cfg, nil
}

func (c Config) Save(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := fmt.Sprintf(`# Generated by csgclaw onboard.

[server]
listen_addr = %q
api_base_url = %q

[llm]
base_url = %q
api_key = %q
model_id = %q

[bootstrap]
manager_image = %q

[picoclaw]
access_token = %q
`, c.Server.ListenAddr, c.Server.APIBaseURL, c.LLM.BaseURL, c.LLM.APIKey, c.LLM.ModelID, c.Bootstrap.ManagerImage, c.PicoClaw.AccessToken)

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}
